### ISSUE TITLE
some request for help 

### ISSUE THREAD

**Issue by chengarthur** [akikuno/DAJIN2#2]
Hi, Dr. Akihiro
I am Chen,a student who recently started benchmark research on CRISPR editing outcome approaches and I am very interested in your previous work DAJIN which used Nano sim results to cluster reads for long reads sequencing genotyping. In my study, I tried to compare the performance of different genotyping methods in a complicated situations like long deletion lesions
However, I met some problems while trying to repeat your methods on my own public dataset. I could not run DAJIN with its basic usage (listed in another issue) and discovered this DAJIN2 repository. would you like to allow me to have a try on DAJIN2 with some brief description and guidelines on my own data? the dataset is like:
Input
Nanopore and Pacbio sequencing outcomes of several certain gRNAs, the sequencing depth and designed gRNAs vary from each sample.
output
Major editing outcomes of editing events with read count and percentage (like DAJIN )
It would be very grateful for me if you could help we with my study, thank you for your time and help
btw, I found the third nanopore data is really noisy and the length of reads is complete certain (some are entire and some lack pieces), how could you handle this low quality reads in DAJIN ,I am not fully understand your work in DAJIN
thank you!

**Comment by akikuno** [comment]
Hi Chen,
Thanks for contacting me.
As I replied to your email, DAJIN2 is now upderconstruction.
I want DAJIN2 to be available by this year.

> btw, I found the third nanopore data is really noisy and the length of reads is complete certain (some are entire and some lack pieces), how could you handle this low quality reads in DAJIN ,I am not fully understand your work in DAJIN

Basically, DAJIN1/2 subtract sequencing errors of samples using a control (= not genome edited sample) so DAJIN1/2 require a control. I hope the `S7 Fig MIDS score` helps you.
[journal.pbio.3001507.s007 (1).pdf](https://github.com/akikuno/DAJIN2/files/9612512/journal.pbio.3001507.s007.1.pdf)

In addition, DAJIN1/2 discard the imcomplete reads. The definition of imcomplete reads in DAJIN is that the reads with 50 bases deletion at either left or right ends of the expected sequence.

**Comment by chengarthur** [comment]
thank you for your reply and help! it's very useful~
